### PR TITLE
Added more Yoast data to the Schema

### PR DESCRIPTION
**Pull request by izzygld**
**Added the following Yoast data to the Schema:**

**SEO** -  opengraphUrl, opengraphSiteName, opengraphPublishedTime, opengraphModifiedTime.

**SEOSchema** - siteName, wordpressSiteName, siteUrl.

### CODE REVIEW

**Comment by ashhitch** [comment]
@izzygld Thanks for adding these!

**Comment by ashhitch** [comment]
@izzygld was just going to create a version release with your changes when I tested the extra data in the schema:

- siteName
-  siteUrl
-  wordpressSiteName
They return null, do they return for you? also where in the Yoast plugin are these?

**Comment by izzygld** [comment]
Should be the 
site_name = _The site name from the Yoast SEO settings_.
wordpress_site_name = _The site name from the WordPress settings._
site_url = _The main URL for the site._

Screen Shot 2020-05-06 at 8 25 55
- see [https://developer.yoast.com/blog/yoast-seo-14-0-using-yoast-seo-surfaces/](https://developer.yoast.com/blog/yoast-seo-14-0-using-yoast-seo-surfaces/)
Will look into it.

**Comment by ashhitch** [comment]
@izzygld  that table is a bit confusing, as that's data available at a post/ taxonomy level.
I have found the relevant fields and patched it up, thanks for your help.

**Comment by izzygld** [comment]
Thanks.

although it should be on "settings" level.

Can a post have a different value from `"get_site_name()"`?

**Comment by ashhitch** [comment]
Nope, I don't think it can, I think it just exposes there a convenience.

**Comment by izzygld** [comment]
for a multisite,
shouldn't we use:
```
if ( is_multisite() ) {
	return get_network()->site_name;
}
```

**Pull request merged**
