### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by gregrickaby**
By adding this file, you're giving developers the chance to use Composer to manage this as a package.

### CODE REVIEW

**Comment by ashhitch** [comment]
@gregrickaby thanks for contributing, im more than happy to add this to the repo.
Just thinking should we add "wp-graphql/wp-graphql" and "yoast/wordpress-seo" to the require key? as my plugin cannot run without them?

**Comment by gregrickaby** [comment]
🤔 Smart. I'll make that edit!

**Comment by gregrickaby** [comment]
@ashhitch Let me know if you need anything else! 👍

**Comment by ashhitch** [comment]
Thanks @gregrickaby appreciate the contribution.

**Pull request merged**
