### PR TITLE
Move function from the `graphql_register_types` action hook

### LINKED ISSUE #161: Cannot redeclare `get_post_type_graphql_fields()` previously declared
I noticed this bug while adding unit tests in a plugin.

```
PHP Fatal error:  Cannot redeclare get_post_type_graphql_fields() (previously declared in /var/www/project/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php:748) in /var/www/project/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 748

Fatal error: Cannot redeclare get_post_type_graphql_fields() (previously declared in /var/www/project/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php:748) in /var/www/project/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 748
```

The issue seems to be because this function is being instantiated inside the `graphql_register_types` hook action which can be run multiple times.

https://github.com/ashhitch/wp-graphql-yoast-seo/blob/278d751c765dba031fdcbeec1ed0d425a16486be/wp-graphql-yoast-seo.php#L748

### PR DESCRIPTION
**Pull request by renatonascalves**
resolves #161

### CODE REVIEW

**Comment by renatonascalves** [comment]
I wonder if this function's name should be changed as well. 🤔 Into something unique to the plugin.

**Comment by renatonascalves** [comment]
@ashhitch Done! :)

**Comment by renatonascalves** [comment]
@ashhitch Bumping this! 🙏🏾

**Comment by ashhitch** [comment]
All merged in I have another branch with another bug fix will get them released together. 
Thanks 👍

**Pull request merged**
