### PR TITLE
PostTypeSEO improvements: More defensive programming for retrieving $…

### PR DESCRIPTION
**Pull request by matthewgrzegorczyk**
…meta values to prevent errors and warnings

As the building seo array for PostTypeSEO we are relying hard on presence of \Yoast\WP\SEO\Surfaces\Values\Meta instance I've made some basic checks and remove repetitions to call meta->for_post() multiple times, cause it was throwing errors on draft posts, since those don't have the Meta instance and return false instead.

### CODE REVIEW

**Comment by matthewgrzegorczyk** [comment]
Also I thought about fetching the yoast data from original post data for that revision.
We can check the `post_type` if it's equal to revision, then try to fetch yoast seo data for post parent.
Same concept is described right here: https://github.com/Yoast/wordpress-seo/issues/17596

**Comment by ashhitch** [comment]
Hi thanks for this, will give it a good test and look to merge it in.

**Comment by matthewgrzegorczyk** [comment]
Did you had a chance to test it? Maybe I can help you somehow?

**Comment by kamilgrzegorczyk** [comment]
@ashhitch I am sorry for bumping you here. Did you have a chance to take a look?

**Pull request merged**
